CREATE TABLE IF NOT EXISTS report (id VARCHAR(125) PRIMARY KEY, sender VARCHAR(125) NOT NULL, "user" VARCHAR(125) NULL, note VARCHAR(125) NULL, "comment" VARCHAR(10000) NULL, "createdAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "updatedAt" TIMESTAMP NULL);
ALTER TABLE report ADD CONSTRAINT unique_report_id UNIQUE (id);
ALTER TABLE report ADD CONSTRAINT fk_report_sender__id FOREIGN KEY (sender) REFERENCES "user"(id) ON DELETE CASCADE ON UPDATE RESTRICT;
ALTER TABLE report ADD CONSTRAINT fk_report_user__id FOREIGN KEY ("user") REFERENCES "user"(id) ON DELETE CASCADE ON UPDATE RESTRICT;
ALTER TABLE report ADD CONSTRAINT fk_report_note__id FOREIGN KEY (note) REFERENCES note(id) ON DELETE CASCADE ON UPDATE RESTRICT;
