ALTER TABLE emoji ALTER COLUMN "apId" TYPE VARCHAR(10000);
ALTER TABLE emoji ALTER COLUMN "name" TYPE VARCHAR(1000);
ALTER TABLE emoji ALTER COLUMN category TYPE VARCHAR(1000);
ALTER TABLE emoji ALTER COLUMN host TYPE VARCHAR(10000);
ALTER TABLE emoji ALTER COLUMN src TYPE VARCHAR(100000);
