ALTER TABLE note ADD attachments TEXT[] DEFAULT ARRAY[]::text[] NOT NULL;
ALTER TABLE note ALTER COLUMN "apId" TYPE VARCHAR(10000);
ALTER TABLE note ALTER COLUMN conversation TYPE VARCHAR(10000);
ALTER TABLE note ALTER COLUMN cw TYPE VARCHAR(10000);
ALTER TABLE note ALTER COLUMN "content" TYPE VARCHAR(100000);
